project_id = "bdmpshiqspkxcisnnlyr"

[functions.migrate-technologies]
verify_jwt = false

[functions.review-edit]
verify_jwt = false

[functions.ai-search-technologies]
verify_jwt = false

[functions.classify-technologies]
verify_jwt = false

[functions.sync-to-external]
verify_jwt = false

[functions.bulk-sync-to-external]
verify_jwt = false

[functions.move-to-case-studies]
verify_jwt = false
